# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bitrix_auth', '0026_auto_20170122_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitrixChatBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('avatar', models.ImageField(upload_to=b'bitrix/chat_bot_avatars/')),
                ('type', models.CharField(max_length=1)),
                ('domain', models.CharField(max_length=100)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitrix_chat_bots', to='bitrix_auth.BitrixApp')),
            ],
        ),
        migrations.CreateModel(
            name='BitrixRegisteredChatBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitrix_id', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('bx_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bitrix_auth.BitrixUser')),
                ('chat_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitrix_chat_bot.BitrixChatBot')),
            ],
        ),
    ]
