# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app_object_history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='id \u043e\u0431\u044a\u0435\u043a\u0442\u0430')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u0412\u0440\u0435\u043c\u044f')),
                ('message', models.TextField(blank=True, default='', verbose_name='\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='\u0422\u0438\u043f \u043e\u0431\u044a\u0435\u043a\u0442\u0430')),
            ],
            options={
                'verbose_name': '\u0417\u0430\u043f\u0438\u0441\u044c \u0438\u0441\u0442\u043e\u0440\u0438\u0438 \u043e\u0431\u044a\u0435\u043a\u0442\u0430',
                'verbose_name_plural': '\u0418\u0441\u0442\u043e\u0440\u0438\u044f \u043e\u0431\u044a\u0435\u043a\u0442\u043e\u0432',
            },
        ),
        migrations.RemoveField(
            model_name='objecthistoryrecord',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='ObjectHistoryRecord',
        ),
    ]
