# Generated by Django 3.1.6 on 2021-04-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0062_auto_20210301_2250'),
        ('app_logger', '0013_auto_20201129_1326'),
        ('bitrix_adminmode', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='portallog',
            index_together={('app', 'portal')},
        ),
    ]
