# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bitrix_auth', '0046_bitrixusertoken_app_sid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitrixFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.IntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('file_extension', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bitrix_auth.BitrixPortal')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bitrix_auth.BitrixUser')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bitrixfile',
            unique_together=set([('portal', 'file_id')]),
        ),
    ]
