# Generated by Django 2.2.1 on 2023-05-06 18:53

import bitrix_utils.bitrix_disk.models.bitrix_file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_disk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrixfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=bitrix_utils.bitrix_disk.models.bitrix_file.file_path),
        ),
    ]
