# Generated by Django 4.2.4 on 2023-08-30 12:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bitrix_auth', '0064_alter_bitrixapp_is_webhook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSettingsGptConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_expired', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('data', models.JSONField(default=dict)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('gpt_api_key', models.CharField(blank=True, max_length=64, null=True)),
                ('portal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='portal_settings', to='bitrix_auth.bitrixportal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AiTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='Ваш запрос')),
                ('response_content', models.TextField(blank=True, help_text='Ответ GPT', null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, help_text='Время создания запроса')),
                ('callback_url', models.URLField()),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('processed_dt', models.DateTimeField(blank=True, help_text='Время, в которое запрос был выполнен', null=True)),
                ('prompt_tokens', models.IntegerField(blank=True, help_text='Количество израсходованных токенов на запрос', null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True, verbose_name='Количество израсходованных токенов на ответ')),
                ('portal', models.ForeignKey(help_text='Портал с которого был выполнен запрос', on_delete=django.db.models.deletion.CASCADE, to='bitrix_auth.bitrixportal')),
            ],
        ),
    ]
