# Generated by Django 4.2.4 on 2023-08-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gptconnector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitask',
            name='completion_tokens',
            field=models.IntegerField(blank=True, help_text='Количество израсходованных токенов на ответ', null=True),
        ),
    ]
