# Generated by Django 2.1.2 on 2018-11-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
