# -*- coding: utf-8 -*-
# Generated by Django 2.1.5 on 2019-03-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_logger', '0003_rm_script_dupes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedscript',
            name='pathname',
            field=models.CharField(max_length=200, unique=True, verbose_name=u'Путь к скрипту'),
        ),
    ]
