# Generated by Django 2.1.2 on 2019-04-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_logger', '0005_auto_20190422_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedapp',
            name='level_send_telegram',
            field=models.PositiveSmallIntegerField(choices=[(10, 'DEBUG'), (20, 'INFO'), (30, 'WARNING'), (40, 'ERROR'), (50, 'CRITICAL')], default=10, verbose_name='Уровень отсыла в Telegram'),
        ),
        migrations.AddField(
            model_name='loggedscript',
            name='level_send_telegram',
            field=models.PositiveSmallIntegerField(choices=[(10, 'DEBUG'), (20, 'INFO'), (30, 'WARNING'), (40, 'ERROR'), (50, 'CRITICAL')], default=10, verbose_name='Уровень отсыла в Telegram'),
        ),
        migrations.AddField(
            model_name='logtype',
            name='level_send_telegram',
            field=models.PositiveSmallIntegerField(choices=[(10, 'DEBUG'), (20, 'INFO'), (30, 'WARNING'), (40, 'ERROR'), (50, 'CRITICAL')], default=10, verbose_name='Уровень отсыла в Telegram'),
        ),
    ]
