# Generated by Django 2.2.4 on 2019-10-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_logger', '0007_auto_20190906_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtype',
            name='postpone',
            field=models.DateField(blank=True, null=True, verbose_name='Отложить логгирование до'),
        ),
    ]
