# Generated by Django 2.2.1 on 2020-03-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_logger', '0009_logrecord_app_delete_orphans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrecord',
            name='app',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_logger.LoggedApp', verbose_name='Приложение'),
            preserve_default=False,
        ),
    ]
