# Generated by Django 2.2.4 on 2020-04-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_logger', '0010_auto_20200324_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrecord',
            name='tag',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Метка для фильтрации'),
        ),
    ]
