# Generated by Django 2.2.4 on 2020-04-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_logger', '0011_logrecord_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrecord',
            name='tag',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, null=True, verbose_name='Метка для фильтрации'),
        ),
    ]
