# Generated by Django 2.2.14 on 2020-11-29 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_logger', '0012_auto_20200407_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='logrecord',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время'),
        ),
        migrations.AddIndex(
            model_name='logrecord',
            index=models.Index(fields=['date', 'type'], name='app_logger__date_c63a78_idx'),
        ),
    ]
