# Generated by Django 2.2.14 on 2022-03-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_logger', '0013_auto_20201129_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedapp',
            name='level_send_email',
            field=models.PositiveSmallIntegerField(choices=[(10, 'DEBUG'), (20, 'INFO'), (30, 'WARNING'), (40, 'ERROR'), (50, 'CRITICAL')], default=50, verbose_name='Уровень отсыла по E-mail'),
        ),
    ]
