# Generated by Django 4.2.4 on 2023-08-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_logger', '0014_auto_20220316_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrecord',
            name='params',
            field=models.JSONField(blank=True, null=True, verbose_name='Параметры'),
        ),
    ]
