# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cron', '0004_cron_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='cron',
            name='process_filter',
            field=models.PositiveSmallIntegerField(default=1, help_text='\u0412 \u043a\u0430\u043a\u043e\u043c \u043f\u0440\u043e\u0446\u0435\u0441\u0441\u0435 \u0437\u0430\u043f\u0443\u0441\u043a\u0430\u0442\u044c'),
        ),
        migrations.AlterField(
            model_name='cron',
            name='active',
            field=models.BooleanField(default=True, help_text='\u0410\u043a\u0442\u0438\u0432\u0435\u043d \u043a\u0440\u043e\u043d \u0438\u043b\u0438 \u043d\u0435\u0442'),
        ),
        migrations.AlterField(
            model_name='cron',
            name='description',
            field=models.TextField(blank=True, default=b'', help_text='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='cron',
            name='name',
            field=models.CharField(help_text='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u0440\u043e\u043d\u0430 \u0434\u043b\u044f \u0443\u0434\u043e\u0431\u0441\u0442\u0432\u0430', max_length=255),
        ),
        migrations.AlterField(
            model_name='cron',
            name='parameters',
            field=models.TextField(blank=True, help_text='JSON-\u043f\u0430\u0440\u0430\u043c\u0435\u0442\u0440\u044b. \u041e\u0442\u043f\u0440\u0430\u0432\u043b\u044f\u044e\u0442\u0441\u044f \u0432 \u0444\u0443\u043d\u043a\u0446\u0438\u044e.', null=True),
        ),
        migrations.AlterField(
            model_name='cron',
            name='path',
            field=models.CharField(help_text='\u041f\u043e\u043b\u043d\u044b\u0439 \u043f\u0443\u0442\u044c \u0434\u043e \u0444\u0443\u043d\u043a\u0446\u0438\u0438. \u0421\u0438\u043d\u0442\u0430\u043a\u0441\u0438\u0441 \u043a\u0430\u043a \u043f\u0438\u0442\u043e\u043d\u043e\u0432\u0441\u043a\u0438\u0439 \u0438\u043c\u043f\u043e\u0440\u0442.\u041d\u0430\u043f\u0440\u0438\u043c\u0435\u0440 autotasks.t18816_add_row_for_ticket_with_tables.process_autotask', max_length=255),
        ),
        migrations.AlterField(
            model_name='cron',
            name='repeat_seconds',
            field=models.IntegerField(blank=True, help_text='\u0421\u043a\u043e\u043b\u044c\u043a\u043e \u0440\u0430\u0437 \u0432 \u043c\u0438\u043d\u0443\u0442\u0443 \u0437\u0430\u043f\u0443\u0441\u043a\u0430\u0442\u044c \u044d\u0442\u0443 \u0437\u0430\u0434\u0430\u0447\u0443.\u0415\u0441\u043b\u0438 \u043f\u043e\u043b\u0435 \u043e\u043f\u0440\u0435\u0434\u0435\u043b\u0435\u043d\u043e, \u0442\u043e \u043a\u0440\u043e\u043d \u0441\u0442\u0440\u043e\u043a\u0430 \u0438\u0433\u043d\u043e\u0440\u0438\u0440\u0443\u0435\u0442\u0441\u044f', null=True),
        ),
        migrations.AlterField(
            model_name='cron',
            name='string',
            field=models.CharField(blank=True, help_text='\u041a\u0440\u043e\u043d \u0441\u0442\u0440\u043e\u043a\u0430', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cron',
            name='timeout',
            field=models.FloatField(blank=True, help_text='\u0412\u0440\u0435\u043c\u044f, \u0447\u0435\u0440\u0435\u0437 \u043a\u043e\u0442\u043e\u0440\u043e\u0435 \u043e\u0436\u0438\u0434\u0430\u0435\u0442\u0441\u044f \u0432\u044b\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u0435 \u0437\u0430\u0434\u0430\u0447\u0438.', null=True),
        ),
    ]
