# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cron', '0006_auto_20160212_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronresult',
            name='cron_started',
            field=models.DateTimeField(null=True),
        ),
    ]
