# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cron', '0007_cronresult_cron_started'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateField()),
                ('ended', models.DateField()),
            ],
        ),
    ]
