# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cron', '0008_cronlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronlog',
            name='process',
            field=models.IntegerField(default=0),
        ),
    ]
