# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-06 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cron', '0010_auto_20160505_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronlog',
            name='started',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cronlog',
            name='stopped',
            field=models.DateTimeField(null=True),
        ),
    ]
