# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-19 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cron', '0011_auto_20160506_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronlog',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cronresult',
            name='cron_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cron.CronLog'),
        ),
    ]
