# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-24 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cron', '0013_auto_20170519_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronresult',
            name='finished',
            field=models.NullBooleanField(),
        ),
    ]
