# Generated by Django 2.0.7 on 2018-08-21 11:01
# -*- coding: UTF-8 -*-

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cron', '0015_auto_20170524_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cron',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Описание'),
        ),
        migrations.AlterField(
            model_name='cronresult',
            name='cron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_cron.Cron'),
        ),
        migrations.AlterField(
            model_name='cronresult',
            name='cron_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_cron.CronLog'),
        ),
    ]
