# Generated by Django 2.2 on 2019-07-31 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cron', '0016_auto_20180821_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='cron',
            name='started_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cron',
            name='active',
            field=models.BooleanField(blank=True, default=True, help_text='Активен крон или нет'),
        ),
        migrations.AlterField(
            model_name='cronresult',
            name='cron_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cron.CronLog'),
        ),
    ]
