# Generated by Django 2.2 on 2019-07-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cron', '0017_auto_20190731_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cron',
            name='timeout',
            field=models.FloatField(blank=True, default=60, help_text='Время, через которое ожидается выполнение задачи.'),
        ),
    ]
