# Generated by Django 2.2.3 on 2019-07-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cron', '0018_auto_20190731_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cron',
            name='started_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cronresult',
            name='finished',
            field=models.NullBooleanField(db_index=True, default=False),
        ),
    ]
