# Generated by Django 2.2.14 on 2022-12-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cron', '0019_auto_20190731_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronlog',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cronresult',
            name='finished',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
