# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitrixPortal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('member_id', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='BitrixUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('auth_token', models.CharField(max_length=32)),
                ('refresh_token', models.CharField(max_length=32)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitrix_user', to='bitrix_auth.BitrixPortal')),
            ],
        ),
    ]
