# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 14:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrixuser',
            name='auth_token_date',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 10, 14, 26, 31, 701671, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
