# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0003_bitrixuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrixportal',
            name='joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
