# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0004_bitrixportal_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrixportal',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bitrixportal',
            name='scope',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='bitrixuser',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, b'Active'), (1, b'Expired Token')], default=0),
        ),
    ]
