# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0007_auto_20160210_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitrixuser',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Active'), (0, b'Expired Token')], default=1),
        ),
    ]
