# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0008_auto_20160212_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitrixuser',
            name='first_name',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='bitrixuser',
            name='last_name',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
    ]
