# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0013_auto_20160220_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrixuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitrix_auth.BitrixDepartment'),
        ),
    ]
