# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0014_bitrixuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitrixuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bitrix_auth.BitrixDepartment'),
        ),
    ]
