# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0015_auto_20160220_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitrixuser',
            name='department',
        ),
        migrations.AddField(
            model_name='bitrixuser',
            name='departments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bitrixuser',
            name='groups',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
