# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-26 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0018_auto_20160226_1412'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bitrixdepartment',
            managers=[
            ],
        ),
    ]
