# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0020_auto_20161130_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrixapp',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bitrixapp',
            name='bitrix_client_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bitrixapp',
            name='bitrix_client_secret',
            field=models.CharField(max_length=100),
        ),
    ]
