# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0021_auto_20161130_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitrixUserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=32)),
                ('refresh_token', models.CharField(max_length=32)),
                ('auth_token_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('refresh_error', models.PositiveSmallIntegerField(choices=[(0, b'\xd0\x9d\xd0\xb5\xd1\x82 \xd0\xbe\xd1\x88\xd0\xb8\xd0\xb1\xd0\xba\xd0\xb8'), (1, b'\xd0\x9d\xd0\xb5 \xd1\x83\xd1\x81\xd1\x82\xd0\xb0\xd0\xbd\xd0\xbe\xd0\xb2\xd0\xbb\xd0\xb5\xd0\xbd \xd0\xbf\xd0\xbe\xd1\x80\xd1\x82\xd0\xb0\xd0\xbb (Wrong client)'), (2, b'\xd0\xa3\xd1\x81\xd1\x82\xd0\xb0\xd1\x80\xd0\xb5\xd0\xbb \xd0\xba\xd0\xbb\xd1\x8e\xd1\x87 \xd1\x81\xd0\xbe\xd0\xb2\xd1\x81\xd0\xb5\xd0\xbc (Expired token)'), (3, b'\xd0\x98\xd0\xbd\xd0\xb2\xd0\xb0\xd0\xbb\xd0\xb8\xd0\xb4 \xd0\xb3\xd1\x80\xd0\xb0\xd0\xbd\xd1\x82 (Invalid grant)'), (9, b'\xd0\x9d\xd0\xb0\xd0\xb4\xd0\xbe \xd1\x80\xd0\xb0\xd0\xb7\xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd1\x82\xd1\x8c\xd1\x81\xd1\x8f (Unnown Error)')], default=0)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bitrix_auth.BitrixApp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitrix_user_token', to='bitrix_auth.BitrixUser')),
            ],
        ),
    ]
