# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0023_auto_20161209_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitrixAppInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitrix_auth.BitrixApp')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitrix_auth.BitrixPortal')),
            ],
        ),
    ]
