# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0024_bitrixappinstallation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bitrixappinstallation',
            unique_together=set([('portal', 'application')]),
        ),
    ]
