# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-10 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0027_auto_20170216_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrixappinstallation',
            name='installation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
