# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0029_auto_20170616_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrixapp',
            name='domain',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
