# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0030_bitrixapp_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrixapp',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
