# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-19 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0031_bitrixapp_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitrixuser',
            name='departments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bitrixuser',
            name='groups',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
