# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-09 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0032_auto_20180119_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitrixusertoken',
            name='refresh_token',
            field=models.CharField(max_length=70),
        ),
    ]
