# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-01 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0032_auto_20180119_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitrixuser',
            name='departments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitrixuser',
            name='groups',
            field=models.TextField(blank=True, null=True),
        ),
    ]
