# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-09 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0033_auto_20180201_1056'),
        ('bitrix_auth', '0033_auto_20180209_2353'),
    ]

    operations = [
    ]
