# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-12 08:36
from __future__ import unicode_literals

import bitrix_utils.bitrix_auth.models.bitrix_user_token
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0034_merge_20180209_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrixusertoken',
            name='bitrix_request',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, validators=[bitrix_utils.bitrix_auth.models.bitrix_user_token.validate_bitrix_request]),
        ),
        migrations.AddField(
            model_name='bitrixusertoken',
            name='bitrix_response',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitrixusertoken',
            name='process_bitrix_request',
            field=models.BooleanField(default=False),
        ),
    ]
