# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 08:11
from __future__ import unicode_literals

import bitrix_utils.bitrix_auth.models.bitrix_user_token
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0039_auto_20180317_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitrixusertoken',
            name='bitrix_request',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text=b'Example: ["crm.deal.list", {"filter": {"STAGE_ID": "NEW"}}]', null=True, validators=[bitrix_utils.bitrix_auth.models.bitrix_user_token.validate_bitrix_request]),
        ),
    ]
