# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0040_auto_20180326_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrixapp',
            name='is_webhook',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bitrixusertoken',
            name='refresh_token',
            field=models.CharField(blank=True, default=b'', max_length=70),
        ),
    ]
