# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0041_auto_20180326_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitrixapp',
            name='is_webhook',
            field=models.NullBooleanField(default=False),
        ),
    ]
