# -*- coding: utf-8 -*-
# Generated by Django 2.0.7 on 2018-08-21 11:01

import bitrix_utils.bitrix_auth.models.bitrix_user_token
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0042_auto_20180326_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitrixuser',
            name='refresh_error',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Нет ошибки'), (1, 'Не установлен портал (Wrong client)'), (2, 'Устарел ключ совсем (Expired token)'), (3, 'Инвалид грант (Invalid grant)'), (9, 'Надо разобраться (Unnown Error)')], default=0),
        ),
        migrations.AlterField(
            model_name='bitrixusertoken',
            name='bitrix_request',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Example: ["crm.deal.list", {"filter": {"STAGE_ID": "NEW"}}]', null=True, validators=[bitrix_utils.bitrix_auth.models.bitrix_user_token.validate_bitrix_request]),
        ),
        migrations.AlterField(
            model_name='bitrixusertoken',
            name='refresh_error',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Нет ошибки'), (1, 'Не установлен портал (Wrong client)'), (2, 'Устарел ключ совсем (Expired token)'), (3, 'Инвалид грант (Invalid grant)'), (4, 'Не установлен портал (NOT_INSTALLED)'), (5, 'Не оплачено (PAYMENT_REQUIRED)'), (6, 'Домен отключен или не существует'), (8, 'ошибка >= 500 '), (9, 'Надо разобраться (Unknown Error)'), (10, 'PORTAL_DELETED'), (11, 'ERROR_CORE'), (12, 'ERROR_OAUTH'), (13, 'ERROR_403_or_404'), (14, 'NO_AUTH_FOUND'), (15, 'AUTHORIZATION_ERROR'), (16, 'ACCESS_DENIED')], default=0),
        ),
        migrations.AlterField(
            model_name='bitrixusertoken',
            name='refresh_token',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
    ]
