# Generated by Django 2.0.7 on 2018-08-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0043_auto_20180821_1401'),
        ('bitrix_auth', '0043_auto_20180814_1749'),
    ]

    operations = [
    ]
