# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-23 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0044_merge_20180822_1332'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bitrixuser',
            unique_together=set([('portal', 'bitrix_id')]),
        ),
    ]
