# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-17 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0046_bitrixusertoken_app_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrixuser',
            name='departments_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitrixuser',
            name='groups_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitrixuser',
            name='immediate_departments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitrixuser',
            name='immediate_departments_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
