# -*- coding: utf-8 -*-
# Generated by Django 2.2.1 on 2019-05-14 12:47
from __future__ import unicode_literals
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0048_auto_20190320_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrixgroup',
            name='members',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='bitrixdepartment',
            name='head_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitrixdepartment',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitrixdepartment',
            name='users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
