# Generated by Django 2.2.1 on 2019-08-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0049_squash_auto_20190514_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitrixdepartment',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='bitrixdepartment',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='bitrixdepartment',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
