# Generated by Django 2.2.1 on 2019-07-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0049_squash_auto_20190514_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrixuser',
            name='extranet',
            field=models.NullBooleanField(default=None),
        ),
    ]
