# Generated by Django 2.2.1 on 2019-08-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0050_bitrixuser_extranet'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrixgroup',
            name='extranet',
            field=models.NullBooleanField(default=None),
        ),
    ]
