# Generated by Django 2.2.1 on 2019-08-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0050_auto_20190807_1531'),
        ('bitrix_auth', '0051_bitrixgroup_extranet'),
    ]

    operations = [
    ]
