# Generated by Django 2.2.4 on 2019-08-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0053_auto_20190807_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitrixusertoken',
            name='refresh_error',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Нет ошибки'), (1, 'Не установлен портал (Wrong client)'), (2, 'Устарел ключ совсем (Expired token)'), (3, 'Инвалид грант (Invalid grant)'), (4, 'Не установлен портал (NOT_INSTALLED)'), (5, 'Не оплачено (PAYMENT_REQUIRED)'), (6, 'Домен отключен или не существует'), (8, 'ошибка >= 500 '), (9, 'Надо разобраться (Unknown Error)'), (10, 'PORTAL_DELETED'), (11, 'ERROR_CORE'), (12, 'ERROR_OAUTH'), (13, 'ERROR_403_or_404'), (14, 'NO_AUTH_FOUND'), (15, 'AUTHORIZATION_ERROR'), (16, 'ACCESS_DENIED'), (17, 'APPLICATION_NOT_FOUND')], default=0),
        ),
    ]
