# Generated by Django 2.2.1 on 2019-12-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0056_bitrix_app_installation_application_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrixuser',
            name='is_admin_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
