# Generated by Django 2.2.10 on 2020-04-29 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0057_bitrixuser_is_admin_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitrixNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Уведомление'), (1, 'Открытая линия')], default=0)),
                ('message', models.TextField(default='')),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('open_line', models.CharField(blank=True, help_text='только если тип = открытая линия', max_length=500, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitrix_auth.BitrixApp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitrix_notification', to='bitrix_auth.BitrixUser')),
            ],
        ),
    ]
