# Generated by Django 2.2.10 on 2020-05-12 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0058_auto_20200429_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitrixOpenLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('bx_id', models.CharField(max_length=500, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='bitrixnotification',
            name='open_line',
            field=models.ForeignKey(blank=True, help_text='только если тип = открытая линия', null=True, on_delete=django.db.models.deletion.PROTECT, to='bitrix_auth.BitrixOpenLine'),
        ),
    ]
