# Generated by Django 3.1.6 on 2021-03-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0061_auto_20200807_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrixportal',
            name='log_post_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
