# Generated by Django 2.2.14 on 2022-12-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0062_auto_20210301_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitrixdepartment',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='bitrixdepartment',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='bitrixdepartment',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
