# Generated by Django 4.2.4 on 2023-08-30 07:52

import bitrix_utils.bitrix_auth.models.bitrix_user_token
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0063_auto_20221202_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitrixapp',
            name='is_webhook',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='bitrixgroup',
            name='extranet',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bitrixuser',
            name='extranet',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bitrixusertoken',
            name='bitrix_request',
            field=models.JSONField(blank=True, help_text='Example: ["crm.deal.list", {"filter": {"STAGE_ID": "NEW"}}]', null=True, validators=[bitrix_utils.bitrix_auth.models.bitrix_user_token.validate_bitrix_request]),
        ),
        migrations.AlterField(
            model_name='bitrixusertoken',
            name='bitrix_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
