# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_comparative', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compared',
            name='url1',
            field=models.URLField(max_length=255, verbose_name='Url 1'),
        ),
        migrations.AlterField(
            model_name='compared',
            name='url2',
            field=models.URLField(max_length=255, verbose_name='Url 2'),
        ),
    ]
