# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_comparative', '0002_auto_20160915_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet', models.TextField()),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_comparative.Compared')),
            ],
        ),
    ]
