# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_comparative', '0003_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='comparison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_comparative.Compared'),
        ),
    ]
