# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_comparative', '0004_auto_20160922_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='level',
            field=models.IntegerField(default=100),
        ),
    ]
