# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_comparative', '0005_snippet_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='compared',
            name='last_compare',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='level',
            field=models.IntegerField(default=100, help_text='10 - \u043c\u0443\u0441\u043e\u0440 | 20 - script, css | 30 - \u0436\u0434\u0435\u0442 \u0440\u0435\u0448\u0435\u043d\u0438\u044f | 100 - \u0441\u0442\u0430\u0442\u0443\u0441 \u043d\u0435 \u043f\u0440\u0438\u0441\u0432\u043e\u0435\u043d', verbose_name='\u0423\u0440\u043e\u0432\u0435\u043d\u044c'),
        ),
    ]
