# Generated by Django 3.2.5 on 2021-10-08 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_auth', '0062_auto_20210301_2250'),
        ('bitrix_telegram_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalchat',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bitrix_telegram_log.telegramchat'),
        ),
        migrations.AlterUniqueTogether(
            name='portalchat',
            unique_together={('portal', 'app')},
        ),
    ]
