# Generated by Django 3.2.5 on 2021-10-11 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_telegram_log', '0003_alter_portalchat_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChatParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='bitrix_telegram_log.telegramchat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participated_chats', to='bitrix_telegram_log.telegramuser')),
            ],
            options={
                'unique_together': {('chat', 'user')},
            },
        ),
    ]
