# Generated by Django 3.2.5 on 2021-10-18 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_telegram_log', '0004_telegramchatparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalchat',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portalchat',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bitrix_telegram_log.telegramchat', unique=True),
        ),
    ]
