# Generated by Django 3.2.5 on 2021-11-16 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_telegram_log', '0006_auto_20211019_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalchat',
            name='status_message_update_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
