# Generated by Django 3.2.9 on 2022-02-02 16:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_telegram_log', '0007_portalchat_status_message_update_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalchat',
            name='muted_log_types',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
