# -*- coding: utf-8 -*-
# Generated by Django 2.1.7 on 2019-04-01 10:36
from __future__ import unicode_literals
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('active', models.BooleanField(default=True, verbose_name='активна')),
                ('body', froala_editor.fields.FroalaField(verbose_name='тело')),
                ('sort', models.IntegerField(
                    default=500,
                    verbose_name='приоритет',
                    help_text='подсказки с большим приоритетом отображаются '
                              'раньше подсказок с меньшим приоритетом. '
                              'При равенстве приоритетов порядок подсказок '
                              'случайный',
                 )),
            ],
            options={
                'verbose_name': 'подсказка при старте',
                'verbose_name_plural': 'подсказки при старте',
                'ordering': ['-sort', '?'],
            },
        ),
        migrations.CreateModel(
            name='TipCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'категория подсказки',
                'verbose_name_plural': 'категории подсказок',
            },
        ),
        migrations.AddField(
            model_name='tip',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_tips_on_start.TipCategory', verbose_name='категория'),
        ),
        migrations.AlterUniqueTogether(
            name='tip',
            unique_together={('category', 'title')},
        ),
    ]
