# Generated by Django 2.2.1 on 2019-12-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tips_on_start', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='kdb_article_secret',
            field=models.CharField(blank=True, default='', help_text='Заменяет текст и название статьи на статью из Базы Знаний. Код можно посмотреть, зайдя в доступную для редактирования статью и нажав "Получить HTML код ..." в модалке со ссылкой. Пример: 58889_BIDw5EybDJJGT4Ivawn33nLQved7Mc3Dgy2kMBZv9H', max_length=255, verbose_name='секрет статьи из базы знаний'),
        ),
    ]
