# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_logging', '0002_auto_20150929_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logtype',
            name='mute',
        ),
        migrations.AddField(
            model_name='logtype',
            name='level_save_to_db',
            field=models.PositiveSmallIntegerField(choices=[(10, b'DEBUG'), (20, b'INFO'), (30, b'WARNING'), (40, b'ERROR'), (50, b'CRITICAL')], default=10, verbose_name='\u0423\u0440\u043e\u0432\u0435\u043d\u044c \u0437\u0430\u043f\u0438\u0441\u0438 \u0432 \u0411\u0414'),
        ),
        migrations.AddField(
            model_name='logtype',
            name='level_send_email',
            field=models.PositiveSmallIntegerField(choices=[(10, b'DEBUG'), (20, b'INFO'), (30, b'WARNING'), (40, b'ERROR'), (50, b'CRITICAL')], default=10, verbose_name='\u0423\u0440\u043e\u0432\u0435\u043d\u044c \u043e\u0442\u0441\u044b\u043b\u0430 \u043f\u043e E-mail'),
        ),
    ]
