# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-20 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_logging', '0003_auto_20160208_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfromredis',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_logging.LogType', verbose_name='\u0422\u0438\u043f'),
        ),
        migrations.AlterField(
            model_name='logfromredis',
            name='level',
            field=models.IntegerField(choices=[(0, b'NOTSET'), (10, b'DEBUG'), (20, b'INFO'), (30, b'WARNING'), (40, b'ERROR'), (50, b'CRITICAL')], verbose_name='\u0423\u0440\u043e\u0432\u0435\u043d\u044c'),
        ),
    ]
