# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_logging', '0004_auto_20170420_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfromredis',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='\u0414\u0430\u0442\u0430'),
        ),
    ]
