# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-25 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_logging', '0005_logfromredis_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtype',
            name='count_info',
            field=models.CharField(blank=True, default=b'', max_length=255, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0437\u0430\u043f\u0438\u0441\u0435\u0439'),
        ),
        migrations.AddField(
            model_name='logtype',
            name='storage_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0421\u0440\u043e\u043a \u0445\u0440\u0430\u043d\u0435\u043d\u0438\u044f \u0437\u0430\u043f\u0438\u0441\u0435\u0439 (\u0434\u043d\u0438)'),
        ),
    ]
