# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-16 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_logging', '0006_auto_20180125_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logfromredis',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_logging.LogType', verbose_name='\u0422\u0438\u043f'),
        ),
    ]
